Traceback (most recent call last):
  File "/home/alogo/workspace/dockerfiles/ArgoDiffusion/scripts/generation_argo_big_data.py", line 287, in <module>
    print argo.run()
  File "/home/alogo/workspace/dockerfiles/ArgoDiffusion/scripts/generation_argo_big_data.py", line 66, in run
    self.read_file(argofile)
  File "/home/alogo/workspace/dockerfiles/ArgoDiffusion/scripts/generation_argo_big_data.py", line 115, in read_file
    self.model.add_data_line(row)
  File "/home/alogo/workspace/dockerfiles/ArgoDiffusion/scripts/argo_model.py", line 61, in add_data_line
    sys.exit(0)
NameError: global name 'sys' is not defined
