/usr/bin/python: can't open file '/home/vm_user/dockerfiles/ArgoDiffusion/scripts/generation_argo_big_data.py': [Errno 2] No such file or directory
